apiVersion: v1
kind: Secret
metadata:
  name: {{ template "explorer.fullname" . }}
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.explorerPassword }}
  explorer-password: {{ .Values.explorerPassword | b64enc | quote }}
  {{ else }}
  explorer-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.smtpPassword }}
  smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
  {{ end }}
